from sqlmodel import text
from db.database import engine

def migrate_itemcode():
    print("Starting ItemCode Migration (Postgres)...")
    try:
        with engine.connect() as conn:
            # 1. Make Nullable
            print("Ensuring itemCode is nullable...")
            try:
                conn.execute(text("ALTER TABLE products ALTER COLUMN \"itemCode\" DROP NOT NULL;"))
                conn.commit()
                print(" - Set to NULLABLE.")
            except Exception as e:
                print(f" - Error setting nullable (might already be): {e}")
                conn.rollback()

            # 2. Drop Unique Constraint
            # We need to find the name of the constraint.
            print("Finding unique constraint...")
            # Common names generated by SQLAlchemy/Postgres
            # Or query catalog
            
            # Query to find UNIQUE constraints on itemCode
            query = text("""
                SELECT con.conname
                FROM pg_catalog.pg_constraint con
                INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
                INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
                WHERE nsp.nspname = 'public'
                  AND rel.relname = 'products'
                  AND con.contype = 'u';
            """)
            
            # Note: This finds ALL unique constraints on table products. Use carefully.
            # Ideally we check which column it covers, but itemCode is usually the only other unique one besides PK (which is 'p').
            # Let's inspect.
            
            result = conn.execute(query)
            constraints = result.fetchall()
            
            for row in constraints:
                name = row[0]
                # We can't be 100% sure it's itemCode without parsing properties, 
                # but typically it contains "itemCode" or valid approximation if using conventions.
                # Or since user wants NO unique constraints besides PK (which is 'p' type, handled by query filter 'u'),
                # and maybe ItemCode was the only one.
                # Let's check if the constraint involves "itemCode" by looking at definition or just assuming if it's the only one.
                
                # Safer: Try to see if it targets itemCode column.
                # Actually, let's just try the standard naming first.
                pass

            # Try explicit drop if name is standard
            potential_names = ["products_itemCode_key", "ix_products_itemCode"]
            
            dropped = False
            for cname in potential_names:
                try:
                    conn.execute(text(f"ALTER TABLE products DROP CONSTRAINT IF EXISTS \"{cname}\";"))
                    print(f" - Dropped constraint {cname} (if existed).")
                    dropped = True
                except Exception as e:
                    print(f" - Failed to drop {cname}: {e}")
                    conn.rollback()
            
            # Also drop index if it exists (sometimes unique=True creates a unique INDEX, not CONSTRAINT)
            try:
                conn.execute(text("DROP INDEX IF EXISTS \"ix_products_itemCode\";"))
                conn.commit()
                print(" - Dropped Index ix_products_itemCode.")
                dropped = True
            except Exception as e:
                 print(f" - Failed to drop index: {e}")
                 conn.rollback()
            
            if dropped:
                conn.commit()
            else:
                 print("WARNING: Could not find strict unique constraint to drop. Check manually if errors persist.")
            
        print("Migration Complete.")
    except Exception as outer_e:
        print(f"CRITICAL FAIL: {outer_e}")

if __name__ == "__main__":
    migrate_itemcode()
